spring: 
  datasource: 
    url: jdbc:mysql://localhost/cplayersdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
management: 
  endpoints: 
    enabled-by-default: false
    web: 
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true 
server: 
  port: 8081